const TestSuite = @import("tests").tests.TestSuite;
const TestCollection = @import("tests").tests.TestCollection;

pub var base_test_collection = TestCollection{
    .name = "ZFT Base Tests",
    .suites = @constCast(&[_]*TestSuite{
        @constCast(&@import("ft_isalpha.zig").suite),
        @constCast(&@import("ft_isdigit.zig").suite),
        @constCast(&@import("ft_isalnum.zig").suite),
        @constCast(&@import("ft_isascii.zig").suite),
        @constCast(&@import("ft_isprint.zig").suite),
        @constCast(&@import("ft_toupper.zig").suite),
        @constCast(&@import("ft_tolower.zig").suite),
        @constCast(&@import("ft_strlen.zig").suite),
        @constCast(&@import("ft_strchr.zig").suite),
        @constCast(&@import("ft_strrchr.zig").suite),
        @constCast(&@import("ft_strncmp.zig").suite),
        @constCast(&@import("ft_strlcpy.zig").suite),
        @constCast(&@import("ft_strlcat.zig").suite),
        @constCast(&@import("ft_strnstr.zig").suite),
        @constCast(&@import("ft_memset.zig").suite),
        @constCast(&@import("ft_bzero.zig").suite),
        @constCast(&@import("ft_memcpy.zig").suite),
        @constCast(&@import("ft_memmove.zig").suite),
        @constCast(&@import("ft_memchr.zig").suite),
        @constCast(&@import("ft_memcmp.zig").suite),
        @constCast(&@import("ft_atoi.zig").suite),
        @constCast(&@import("ft_calloc.zig").suite),
        @constCast(&@import("ft_strdup.zig").suite),
        @constCast(&@import("ft_substr.zig").suite),
        @constCast(&@import("ft_strjoin.zig").suite),
        @constCast(&@import("ft_strtrim.zig").suite),
        @constCast(&@import("ft_split.zig").suite),
        @constCast(&@import("ft_itoa.zig").suite),
        @constCast(&@import("ft_strmapi.zig").suite),
        @constCast(&@import("ft_striteri.zig").suite),
        // @constCast(&@import("ft_putchar_fd.zig").suite),
        // @constCast(&@import("ft_putstr_fd.zig").suite),
        // @constCast(&@import("ft_putendl_fd.zig").suite),
        // @constCast(&@import("ft_putnbr_fd.zig").suite),
        // @constCast(&@import("ft_lstdelone.zig").suite),
    }),
};

pub var bonus_test_collection = TestCollection{
    .name = "ZFT Bonus Tests",
    .suites = @constCast(&[_]*TestSuite{
        @constCast(&@import("ft_lstnew.zig").suite),
        @constCast(&@import("ft_lstadd_front.zig").suite),
        @constCast(&@import("ft_lstsize.zig").suite),
        @constCast(&@import("ft_lstlast.zig").suite),
        @constCast(&@import("ft_lstadd_back.zig").suite),
        @constCast(&@import("ft_lstdelone.zig").suite),
        @constCast(&@import("ft_lstclear.zig").suite),
        @constCast(&@import("ft_lstiter.zig").suite),
        @constCast(&@import("ft_lstmap.zig").suite),
    }),
};
