const TestSuite = @import("test-framework").tests.TestSuite;
const TestCollection = @import("test-framework").tests.TestCollection;

pub var mandatory_test_collection = TestCollection{
    .name = "ZFT Mandatory Tests",
    .suites = &[_]*TestSuite{
        &@import("ft_isalpha.zig").suite,
        &@import("ft_isdigit.zig").suite,
        &@import("ft_isalnum.zig").suite,
        &@import("ft_isascii.zig").suite,
        &@import("ft_isprint.zig").suite,
        &@import("ft_toupper.zig").suite,
        &@import("ft_tolower.zig").suite,
        &@import("ft_strlen.zig").suite,
        &@import("ft_strchr.zig").suite,
        &@import("ft_strrchr.zig").suite,
        &@import("ft_strncmp.zig").suite,
        &@import("ft_strlcpy.zig").suite,
        &@import("ft_strlcat.zig").suite,
        &@import("ft_strnstr.zig").suite,
        &@import("ft_memset.zig").suite,
        &@import("ft_bzero.zig").suite,
        &@import("ft_memcpy.zig").suite,
        &@import("ft_memmove.zig").suite,
        &@import("ft_memchr.zig").suite,
        &@import("ft_memcmp.zig").suite,
        &@import("ft_atoi.zig").suite,
        &@import("ft_calloc.zig").suite,
        &@import("ft_strdup.zig").suite,
        &@import("ft_substr.zig").suite,
        &@import("ft_strjoin.zig").suite,
        &@import("ft_strtrim.zig").suite,
        &@import("ft_split.zig").suite,
        &@import("ft_itoa.zig").suite,
        &@import("ft_strmapi.zig").suite,
        &@import("ft_striteri.zig").suite,
        &@import("ft_putchar_fd.zig").suite,
        &@import("ft_putstr_fd.zig").suite,
        &@import("ft_putendl_fd.zig").suite,
        &@import("ft_putnbr_fd.zig").suite,
    },
};
